version: "3"

services:
    mongo:
        container_name: mongo
        image: mongo
        restart: always
        ports:
            - "27017:27017"
        networks:
            webappnetwork:
                ipv4_address: "172.96.240.12"
    api:
        container_name: api
        build: ./Server
        restart: always
        ports:
            - "5000:5000"
        volumes:
            - ./Server:/api/
            - /Server/node_modules
        environment:
            - DB_URL=172.96.240.12
            - DB_URL=27017
            - API_URL=172.96.240.11
            - API_PORT=5000
        depends_on:
            - mongo
        networks:
            webappnetwork:
                ipv4_address: "172.96.240.11"
    client:
        container_name: client
        build: ./client
        restart: always
        ports:
            - "3000:3000"
        volumes:
            - ./client:/client/
            - /client/node_modules
        environment:
            - API_URL=http://172.96.240.11:5000
        depends_on:
            - mongo
            - api
        networks:
            webappnetwork:
                ipv4_address: "172.96.240.10"
networks:
    webappnetwork:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.96.240.0/24
